import turtle


turtle.speed(0)
turtle.bgcolor("black")
turtle.pencolor("red")
turtle.fillcolor("blue")
turtle.begin_fill()

for x in range(36):
    turtle.forward(100)
    turtle.right(40)
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(13)
    turtle.left(49)
    turtle.forward(100)
    turtle.right(40)
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(13)
    turtle.left(56)
    turtle.forward(100)
    turtle.right(40)
    turtle.forward(100)
    turtle.right(80)
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(13)
    turtle.left(49)
    turtle.forward(100)
    turtle.right(40)
    turtle.forward(100)
    turtle.right(80)
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(13)
    turtle.left(49)

turtle.end_fill()
turtle.done()
